// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	DeviceTokenScopes deviceTokenContextKey = "deviceToken.Scopes"
)

// Defines values for AchievementKind.
const (
	AchievementKindMilestone AchievementKind = "milestone"
	AchievementKindMonth     AchievementKind = "month"
	AchievementKindRecord    AchievementKind = "record"
	AchievementKindStreak    AchievementKind = "streak"
	AchievementKindYear      AchievementKind = "year"
)

// Valid indicates whether the value is a known member of the AchievementKind enum.
func (e AchievementKind) Valid() bool {
	switch e {
	case AchievementKindMilestone:
		return true
	case AchievementKindMonth:
		return true
	case AchievementKindRecord:
		return true
	case AchievementKindStreak:
		return true
	case AchievementKindYear:
		return true
	default:
		return false
	}
}

// Defines values for AchievementInputKind.
const (
	AchievementInputKindMilestone AchievementInputKind = "milestone"
	AchievementInputKindMonth     AchievementInputKind = "month"
	AchievementInputKindRecord    AchievementInputKind = "record"
	AchievementInputKindStreak    AchievementInputKind = "streak"
	AchievementInputKindYear      AchievementInputKind = "year"
)

// Valid indicates whether the value is a known member of the AchievementInputKind enum.
func (e AchievementInputKind) Valid() bool {
	switch e {
	case AchievementInputKindMilestone:
		return true
	case AchievementInputKindMonth:
		return true
	case AchievementInputKindRecord:
		return true
	case AchievementInputKindStreak:
		return true
	case AchievementInputKindYear:
		return true
	default:
		return false
	}
}

// Defines values for DevicePlatform.
const (
	DevicePlatformIos     DevicePlatform = "ios"
	DevicePlatformIpados  DevicePlatform = "ipados"
	DevicePlatformMacos   DevicePlatform = "macos"
	DevicePlatformWatchos DevicePlatform = "watchos"
	DevicePlatformWeb     DevicePlatform = "web"
)

// Valid indicates whether the value is a known member of the DevicePlatform enum.
func (e DevicePlatform) Valid() bool {
	switch e {
	case DevicePlatformIos:
		return true
	case DevicePlatformIpados:
		return true
	case DevicePlatformMacos:
		return true
	case DevicePlatformWatchos:
		return true
	case DevicePlatformWeb:
		return true
	default:
		return false
	}
}

// Defines values for ExportJobStatus.
const (
	Failed  ExportJobStatus = "failed"
	Pending ExportJobStatus = "pending"
	Ready   ExportJobStatus = "ready"
)

// Valid indicates whether the value is a known member of the ExportJobStatus enum.
func (e ExportJobStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Pending:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for ExportRequestFormat.
const (
	Csv  ExportRequestFormat = "csv"
	Json ExportRequestFormat = "json"
	Pdf  ExportRequestFormat = "pdf"
)

// Valid indicates whether the value is a known member of the ExportRequestFormat enum.
func (e ExportRequestFormat) Valid() bool {
	switch e {
	case Csv:
		return true
	case Json:
		return true
	case Pdf:
		return true
	default:
		return false
	}
}

// Defines values for GoalMetric.
const (
	GoalMetricActiveEnergy GoalMetric = "activeEnergy"
	GoalMetricExerciseTime GoalMetric = "exerciseTime"
	GoalMetricStandHours   GoalMetric = "standHours"
	GoalMetricStepCount    GoalMetric = "stepCount"
)

// Valid indicates whether the value is a known member of the GoalMetric enum.
func (e GoalMetric) Valid() bool {
	switch e {
	case GoalMetricActiveEnergy:
		return true
	case GoalMetricExerciseTime:
		return true
	case GoalMetricStandHours:
		return true
	case GoalMetricStepCount:
		return true
	default:
		return false
	}
}

// Defines values for GoalSource.
const (
	GoalSourceHealthkit GoalSource = "healthkit"
	GoalSourceUser      GoalSource = "user"
)

// Valid indicates whether the value is a known member of the GoalSource enum.
func (e GoalSource) Valid() bool {
	switch e {
	case GoalSourceHealthkit:
		return true
	case GoalSourceUser:
		return true
	default:
		return false
	}
}

// Defines values for GoalUpdateMetric.
const (
	GoalUpdateMetricActiveEnergy GoalUpdateMetric = "activeEnergy"
	GoalUpdateMetricExerciseTime GoalUpdateMetric = "exerciseTime"
	GoalUpdateMetricStandHours   GoalUpdateMetric = "standHours"
	GoalUpdateMetricStepCount    GoalUpdateMetric = "stepCount"
)

// Valid indicates whether the value is a known member of the GoalUpdateMetric enum.
func (e GoalUpdateMetric) Valid() bool {
	switch e {
	case GoalUpdateMetricActiveEnergy:
		return true
	case GoalUpdateMetricExerciseTime:
		return true
	case GoalUpdateMetricStandHours:
		return true
	case GoalUpdateMetricStepCount:
		return true
	default:
		return false
	}
}

// Defines values for GoalUpdateSource.
const (
	GoalUpdateSourceHealthkit GoalUpdateSource = "healthkit"
	GoalUpdateSourceUser      GoalUpdateSource = "user"
)

// Valid indicates whether the value is a known member of the GoalUpdateSource enum.
func (e GoalUpdateSource) Valid() bool {
	switch e {
	case GoalUpdateSourceHealthkit:
		return true
	case GoalUpdateSourceUser:
		return true
	default:
		return false
	}
}

// Defines values for InsightKind.
const (
	Anomaly     InsightKind = "anomaly"
	Correlation InsightKind = "correlation"
	Pattern     InsightKind = "pattern"
	Trend       InsightKind = "trend"
)

// Valid indicates whether the value is a known member of the InsightKind enum.
func (e InsightKind) Valid() bool {
	switch e {
	case Anomaly:
		return true
	case Correlation:
		return true
	case Pattern:
		return true
	case Trend:
		return true
	default:
		return false
	}
}

// Defines values for InsightSeverity.
const (
	Info   InsightSeverity = "info"
	Notice InsightSeverity = "notice"
)

// Valid indicates whether the value is a known member of the InsightSeverity enum.
func (e InsightSeverity) Valid() bool {
	switch e {
	case Info:
		return true
	case Notice:
		return true
	default:
		return false
	}
}

// Defines values for MetricSeriesAgg.
const (
	Avg MetricSeriesAgg = "avg"
	Sum MetricSeriesAgg = "sum"
)

// Valid indicates whether the value is a known member of the MetricSeriesAgg enum.
func (e MetricSeriesAgg) Valid() bool {
	switch e {
	case Avg:
		return true
	case Sum:
		return true
	default:
		return false
	}
}

// Defines values for PushRegisterEnvironment.
const (
	Prod    PushRegisterEnvironment = "prod"
	Sandbox PushRegisterEnvironment = "sandbox"
)

// Valid indicates whether the value is a known member of the PushRegisterEnvironment enum.
func (e PushRegisterEnvironment) Valid() bool {
	switch e {
	case Prod:
		return true
	case Sandbox:
		return true
	default:
		return false
	}
}

// Defines values for PushRegisterPlatform.
const (
	PushRegisterPlatformIos     PushRegisterPlatform = "ios"
	PushRegisterPlatformIpados  PushRegisterPlatform = "ipados"
	PushRegisterPlatformMacos   PushRegisterPlatform = "macos"
	PushRegisterPlatformWatchos PushRegisterPlatform = "watchos"
)

// Valid indicates whether the value is a known member of the PushRegisterPlatform enum.
func (e PushRegisterPlatform) Valid() bool {
	switch e {
	case PushRegisterPlatformIos:
		return true
	case PushRegisterPlatformIpados:
		return true
	case PushRegisterPlatformMacos:
		return true
	case PushRegisterPlatformWatchos:
		return true
	default:
		return false
	}
}

// Defines values for SampleInSourceDevice.
const (
	Iphone SampleInSourceDevice = "iphone"
	Watch  SampleInSourceDevice = "watch"
)

// Valid indicates whether the value is a known member of the SampleInSourceDevice enum.
func (e SampleInSourceDevice) Valid() bool {
	switch e {
	case Iphone:
		return true
	case Watch:
		return true
	default:
		return false
	}
}

// Defines values for SettingsLocale.
const (
	En SettingsLocale = "en"
	Hu SettingsLocale = "hu"
)

// Valid indicates whether the value is a known member of the SettingsLocale enum.
func (e SettingsLocale) Valid() bool {
	switch e {
	case En:
		return true
	case Hu:
		return true
	default:
		return false
	}
}

// Defines values for SettingsUnitSystem.
const (
	Imperial SettingsUnitSystem = "imperial"
	Metric   SettingsUnitSystem = "metric"
)

// Valid indicates whether the value is a known member of the SettingsUnitSystem enum.
func (e SettingsUnitSystem) Valid() bool {
	switch e {
	case Imperial:
		return true
	case Metric:
		return true
	default:
		return false
	}
}

// Defines values for SleepSegmentInStage.
const (
	AsleepCore        SleepSegmentInStage = "asleepCore"
	AsleepDeep        SleepSegmentInStage = "asleepDeep"
	AsleepREM         SleepSegmentInStage = "asleepREM"
	AsleepUnspecified SleepSegmentInStage = "asleepUnspecified"
	Awake             SleepSegmentInStage = "awake"
	InBed             SleepSegmentInStage = "inBed"
)

// Valid indicates whether the value is a known member of the SleepSegmentInStage enum.
func (e SleepSegmentInStage) Valid() bool {
	switch e {
	case AsleepCore:
		return true
	case AsleepDeep:
		return true
	case AsleepREM:
		return true
	case AsleepUnspecified:
		return true
	case Awake:
		return true
	case InBed:
		return true
	default:
		return false
	}
}

// Defines values for GetSummaryParamsRange.
const (
	Day   GetSummaryParamsRange = "day"
	Month GetSummaryParamsRange = "month"
	Week  GetSummaryParamsRange = "week"
	Year  GetSummaryParamsRange = "year"
)

// Valid indicates whether the value is a known member of the GetSummaryParamsRange enum.
func (e GetSummaryParamsRange) Valid() bool {
	switch e {
	case Day:
		return true
	case Month:
		return true
	case Week:
		return true
	case Year:
		return true
	default:
		return false
	}
}

// Achievement defines model for Achievement.
type Achievement struct {
	// Code The specific badge within the family (e.g. `complete`, `3`, `best-month`, `total-1000000`).
	Code     string    `json:"code"`
	EarnedAt time.Time `json:"earned_at"`

	// Id A stable identifier formed by the client — `<kind>:<code>[:<period>]`, e.g. `month:complete:2026-08`, `streak:3:2026-08`, `record:best-month`, `milestone:total-1000000`. This is what gives idempotency: the same badge stays one row however many times it is uploaded.
	Id   string          `json:"id"`
	Kind AchievementKind `json:"kind"`

	// Period `YYYY-MM` or `YYYY`, if the badge belongs to a calendar period.
	Period *string `json:"period,omitempty"`

	// Thresholds A snapshot of the thresholds that were IN FORCE when it was earned. A monthly badge's card can be redrawn from this (and from `period`) — the path is deterministic given the month, so no image has to be stored.
	Thresholds *[]int  `json:"thresholds,omitempty"`
	Unit       *string `json:"unit,omitempty"`

	// Value The figure as it stood when earned (monthly step count, streak length, the record's value).
	Value *float32 `json:"value,omitempty"`
}

// AchievementKind defines model for Achievement.Kind.
type AchievementKind string

// AchievementInput defines model for AchievementInput.
type AchievementInput struct {
	Code string `json:"code"`

	// EarnedAt Only matters for a NEW badge; for an existing one the server keeps the original. The client sends the moment it first saw the condition met — which may well be the first sync long after the end of the month.
	EarnedAt   time.Time            `json:"earned_at"`
	Id         string               `json:"id"`
	Kind       AchievementInputKind `json:"kind"`
	Period     *string              `json:"period,omitempty"`
	Thresholds *[]int               `json:"thresholds,omitempty"`
	Unit       *string              `json:"unit,omitempty"`
	Value      *float32             `json:"value,omitempty"`
}

// AchievementInputKind defines model for AchievementInput.Kind.
type AchievementInputKind string

// ActivitySummary defines model for ActivitySummary.
type ActivitySummary struct {
	ActiveEnergy     *float32            `json:"active_energy,omitempty"`
	ActiveEnergyGoal *float32            `json:"active_energy_goal,omitempty"`
	Day              *openapi_types.Date `json:"day,omitempty"`
	ExerciseGoal     *float32            `json:"exercise_goal,omitempty"`
	ExerciseMinutes  *float32            `json:"exercise_minutes,omitempty"`
	StandGoal        *float32            `json:"stand_goal,omitempty"`
	StandHours       *float32            `json:"stand_hours,omitempty"`
}

// Device defines model for Device.
type Device struct {
	// Id the server-side identifier; optional on POST (if given, that row is updated)
	Id *openapi_types.UUID `json:"id,omitempty"`

	// LastSeenAt set by the server: the time of the most recent POST /devices, or of an /ingest that came from the device
	LastSeenAt *time.Time `json:"last_seen_at,omitempty"`

	// Model e.g. iPhone17,1 — together with the platform this is the key of the upsert without an `id`
	Model    *string        `json:"model,omitempty"`
	Name     *string        `json:"name,omitempty"`
	Platform DevicePlatform `json:"platform"`

	// TimeZone the device's current IANA tz
	TimeZone *string `json:"time_zone,omitempty"`
}

// DevicePlatform defines model for Device.Platform.
type DevicePlatform string

// ExportJob The shape of the asynchronous export branch. **No such object is produced today** — the export is synchronous and `POST /v1/export` hands back the file. The schema stays for a future introduction.
type ExportJob struct {
	ExpiresAt *time.Time          `json:"expires_at,omitempty"`
	ExportId  *openapi_types.UUID `json:"export_id,omitempty"`
	Status    *ExportJobStatus    `json:"status,omitempty"`
	Url       *string             `json:"url,omitempty"`
}

// ExportJobStatus defines model for ExportJob.Status.
type ExportJobStatus string

// ExportRequest defines model for ExportRequest.
type ExportRequest struct {
	Format  ExportRequestFormat `json:"format"`
	From    *openapi_types.Date `json:"from,omitempty"`
	Metrics *[]string           `json:"metrics,omitempty"`
	To      *openapi_types.Date `json:"to,omitempty"`
}

// ExportRequestFormat defines model for ExportRequest.Format.
type ExportRequestFormat string

// Goal defines model for Goal.
type Goal struct {
	// HkValue the last HealthKit goal seen
	HkValue     *float32    `json:"hk_value,omitempty"`
	Metric      *GoalMetric `json:"metric,omitempty"`
	Source      *GoalSource `json:"source,omitempty"`
	TargetValue *float32    `json:"target_value,omitempty"`
	Unit        *string     `json:"unit,omitempty"`
	UpdatedAt   *time.Time  `json:"updated_at,omitempty"`
}

// GoalMetric defines model for Goal.Metric.
type GoalMetric string

// GoalSource defines model for Goal.Source.
type GoalSource string

// GoalUpdate defines model for GoalUpdate.
type GoalUpdate struct {
	HkValue     *float32          `json:"hk_value,omitempty"`
	Metric      GoalUpdateMetric  `json:"metric"`
	Source      *GoalUpdateSource `json:"source,omitempty"`
	TargetValue float32           `json:"target_value"`
}

// GoalUpdateMetric defines model for GoalUpdate.Metric.
type GoalUpdateMetric string

// GoalUpdateSource defines model for GoalUpdate.Source.
type GoalUpdateSource string

// IngestAccepted The body of the 202 response. `received` gives the item counts the server TOOK IN (not processed) — the actual write happens in the worker. This is how the client can check that the chunk arrived complete, and `batch_id` correlates it with the server log when debugging a long backlog drain.
type IngestAccepted struct {
	// BatchId for log correlation
	BatchId *openapi_types.UUID `json:"batch_id,omitempty"`

	// MaxItems The server's current chunk limit — the client can size its next piece to it.
	MaxItems *int `json:"max_items,omitempty"`
	Received *struct {
		ActivitySummaries *int `json:"activity_summaries,omitempty"`
		Deletions         *int `json:"deletions,omitempty"`
		Samples           *int `json:"samples,omitempty"`
		SleepSegments     *int `json:"sleep_segments,omitempty"`
		Workouts          *int `json:"workouts,omitempty"`
	} `json:"received,omitempty"`
}

// IngestBatch One CHUNK of the delta read from the HealthKit anchor (see the description of POST /ingest).
type IngestBatch struct {
	ActivitySummaries *[]ActivitySummary `json:"activity_summaries,omitempty"`

	// Deletions the source_uuids of items deleted in HealthKit (samples/workouts/sleep)
	Deletions     *[]string           `json:"deletions,omitempty"`
	DeviceId      *openapi_types.UUID `json:"device_id,omitempty"`
	Samples       *[]SampleIn         `json:"samples,omitempty"`
	SleepSegments *[]SleepSegmentIn   `json:"sleep_segments,omitempty"`

	// TimeZone the device's current IANA tz
	TimeZone *string      `json:"time_zone,omitempty"`
	Workouts *[]WorkoutIn `json:"workouts,omitempty"`
}

// Insight defines model for Insight.
type Insight struct {
	Detail      *string    `json:"detail,omitempty"`
	GeneratedAt *time.Time `json:"generated_at,omitempty"`

	// Id An identifier of the form `<rule>:<day>`, STABLE WITHIN A DAY (e.g. `resting-hr-elevated:2026-08-11`) — the same statement on the same day always gets the same id, so the client can deduplicate it or mark it as dismissed.
	Id *string `json:"id,omitempty"`

	// Kind What SHAPE of statement this is. `trend` compares a window with the one before it, `anomaly` compares recent days with a longer baseline, `correlation` reports co-movement of two series, and `pattern` describes a property of one window — how much bedtime scatters, how the weekend differs from the week. A `pattern` is not a change over time, which is why it is not a `trend`.
	Kind     *InsightKind     `json:"kind,omitempty"`
	Metric   *string          `json:"metric,omitempty"`
	Severity *InsightSeverity `json:"severity,omitempty"`
	Title    *string          `json:"title,omitempty"`
}

// InsightKind What SHAPE of statement this is. `trend` compares a window with the one before it, `anomaly` compares recent days with a longer baseline, `correlation` reports co-movement of two series, and `pattern` describes a property of one window — how much bedtime scatters, how the weekend differs from the week. A `pattern` is not a change over time, which is why it is not a `trend`.
type InsightKind string

// InsightSeverity defines model for Insight.Severity.
type InsightSeverity string

// MetricSeries One metric's time series, broken into buckets.
//
// ⚠️ **Percentage convention:** wherever `unit` is `%`, the `total` and the bucket values come back in the **0…100** range (19.2% body fat is `19.24`). HealthKit itself gives a 0…1 fraction (`HKUnit.percent()`), and **storage deliberately stays raw**; the multiplication by 100 happens ONCE, on the server's read path. The client must therefore **not scale again** — it should only append the `%` sign. The same convention holds in the `GET /samples` and `POST /export` responses. See `docs/23` §3.0.1.
type MetricSeries struct {
	Agg     *MetricSeriesAgg `json:"agg,omitempty"`
	Buckets *[]struct {
		Avg *float32 `json:"avg,omitempty"`
		Max *float32 `json:"max,omitempty"`
		Min *float32 `json:"min,omitempty"`
		T   *string  `json:"t,omitempty"`
		V   *float32 `json:"v,omitempty"`
	} `json:"buckets,omitempty"`
	Total *float32 `json:"total,omitempty"`

	// Unit The unit sent by the SERVER is authoritative; the client-side catalog is only a fallback.
	Unit *string `json:"unit,omitempty"`
}

// MetricSeriesAgg defines model for MetricSeries.Agg.
type MetricSeriesAgg string

// NotifPrefs defines model for NotifPrefs.
type NotifPrefs struct {
	GoalNudges    *bool `json:"goal_nudges,omitempty"`
	Insights      *bool `json:"insights,omitempty"`
	SyncErrors    *bool `json:"sync_errors,omitempty"`
	WeeklySummary *bool `json:"weekly_summary,omitempty"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   *int    `json:"status,omitempty"`
	Title    *string `json:"title,omitempty"`
	Type     *string `json:"type,omitempty"`
}

// PushRegister defines model for PushRegister.
type PushRegister struct {
	DeviceId    *openapi_types.UUID      `json:"device_id,omitempty"`
	Environment *PushRegisterEnvironment `json:"environment,omitempty"`
	Platform    PushRegisterPlatform     `json:"platform"`

	// Token APNs device token
	Token string `json:"token"`
}

// PushRegisterEnvironment defines model for PushRegister.Environment.
type PushRegisterEnvironment string

// PushRegisterPlatform defines model for PushRegister.Platform.
type PushRegisterPlatform string

// RoutePoint defines model for RoutePoint.
type RoutePoint struct {
	AccuracyM *float32  `json:"accuracy_m,omitempty"`
	AltitudeM *float32  `json:"altitude_m,omitempty"`
	Lat       float64   `json:"lat"`
	Lon       float64   `json:"lon"`
	SpeedMps  *float32  `json:"speed_mps,omitempty"`
	Ts        time.Time `json:"ts"`
}

// Sample defines model for Sample.
type Sample struct {
	DataType     *string    `json:"data_type,omitempty"`
	SourceDevice *string    `json:"source_device,omitempty"`
	Ts           *time.Time `json:"ts,omitempty"`
	Unit         *string    `json:"unit,omitempty"`
	Value        *float32   `json:"value,omitempty"`
}

// SampleIn defines model for SampleIn.
type SampleIn struct {
	// DataType The short name of the HealthKit type, without the `HKQuantityTypeIdentifier`/`HKCategoryTypeIdentifier` prefix, in lowerCamelCase — e.g. `stepCount`, `dietaryEnergyConsumed`, `bodyMass`, `oxygenSaturation`.
	//
	// **DELIBERATELY AN OPEN STRING, NOT AN ENUM.** HealthKit offers well over a hundred quantity types, and the set grows with every iOS release; with a closed enum, every new type would require a contract change, a code regeneration and a deploy. On the storage side `samples.data_type` is `text` anyway.
	//
	// The catalog of supported types and their units: `docs/23-healthkit-katalogus.md`. The server accepts and stores an unknown type — better to have the data than to let a new iOS version silently drop it.
	DataType     string                `json:"data_type"`
	SourceBundle *string               `json:"source_bundle,omitempty"`
	SourceDevice *SampleInSourceDevice `json:"source_device,omitempty"`
	SourceUuid   string                `json:"source_uuid"`
	Ts           time.Time             `json:"ts"`
	Unit         *string               `json:"unit,omitempty"`
	Value        *float32              `json:"value,omitempty"`

	// WorkoutSourceUuid The **HKWorkout.uuid** of the related workout (not the server-side `workouts.id` — the client does not know that). The worker resolves it to a `workouts.id`; if the workout only arrives in a LATER chunk, the resolution is filled in then. `Workout.avg_heart_rate`/`max_heart_rate` build on this.
	WorkoutSourceUuid *string `json:"workout_source_uuid,omitempty"`
}

// SampleInSourceDevice defines model for SampleIn.SourceDevice.
type SampleInSourceDevice string

// SamplePage defines model for SamplePage.
type SamplePage struct {
	Items      *[]Sample `json:"items,omitempty"`
	NextCursor *string   `json:"next_cursor,omitempty"`
}

// Session defines model for Session.
type Session struct {
	AccessToken *string `json:"access_token,omitempty"`
	ExpiresIn   *int    `json:"expires_in,omitempty"`

	// RefreshToken for the native clients; on the web it lives in an httpOnly cookie
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// Settings defines model for Settings.
type Settings struct {
	Locale     *SettingsLocale `json:"locale,omitempty"`
	NotifPrefs *NotifPrefs     `json:"notif_prefs,omitempty"`

	// TimeZone IANA tz, e.g. Europe/Budapest
	TimeZone   *string             `json:"time_zone,omitempty"`
	UnitSystem *SettingsUnitSystem `json:"unit_system,omitempty"`
}

// SettingsLocale defines model for Settings.Locale.
type SettingsLocale string

// SettingsUnitSystem defines model for Settings.UnitSystem.
type SettingsUnitSystem string

// SleepSegment defines model for SleepSegment.
type SleepSegment struct {
	EndedAt   *time.Time `json:"ended_at,omitempty"`
	Stage     *string    `json:"stage,omitempty"`
	StartedAt *time.Time `json:"started_at,omitempty"`
}

// SleepSegmentIn defines model for SleepSegmentIn.
type SleepSegmentIn struct {
	EndedAt    time.Time           `json:"ended_at"`
	SourceUuid string              `json:"source_uuid"`
	Stage      SleepSegmentInStage `json:"stage"`
	StartedAt  time.Time           `json:"started_at"`
}

// SleepSegmentInStage defines model for SleepSegmentIn.Stage.
type SleepSegmentInStage string

// SummaryResponse defines model for SummaryResponse.
type SummaryResponse struct {
	From    *openapi_types.Date      `json:"from,omitempty"`
	Metrics *map[string]MetricSeries `json:"metrics,omitempty"`
	Range   *string                  `json:"range,omitempty"`
	To      *openapi_types.Date      `json:"to,omitempty"`
	Tz      *string                  `json:"tz,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	DisplayName *string             `json:"display_name,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Settings    *Settings           `json:"settings,omitempty"`
}

// Workout defines model for Workout.
type Workout struct {
	ActivityType    *string                 `json:"activity_type,omitempty"`
	AvgHeartRate    *float32                `json:"avg_heart_rate,omitempty"`
	EndedAt         *time.Time              `json:"ended_at,omitempty"`
	Id              *openapi_types.UUID     `json:"id,omitempty"`
	MaxHeartRate    *float32                `json:"max_heart_rate,omitempty"`
	Metadata        *map[string]interface{} `json:"metadata,omitempty"`
	SourceUuid      *string                 `json:"source_uuid,omitempty"`
	StartedAt       *time.Time              `json:"started_at,omitempty"`
	TotalDistanceM  *float32                `json:"total_distance_m,omitempty"`
	TotalEnergyKcal *float32                `json:"total_energy_kcal,omitempty"`
}

// WorkoutIn defines model for WorkoutIn.
type WorkoutIn struct {
	ActivityType string                  `json:"activity_type"`
	EndedAt      *time.Time              `json:"ended_at,omitempty"`
	Metadata     *map[string]interface{} `json:"metadata,omitempty"`

	// Route The GPS route, if there is one (`HKWorkoutRoute`). **The client must count the points against its chunk budget** — the route of a long hike is on its own bigger than an entire helping of samples, and chunking (docs/04 §6.2) exists precisely to avoid giant batches.
	Route           *[]RoutePoint `json:"route,omitempty"`
	SourceUuid      string        `json:"source_uuid"`
	StartedAt       time.Time     `json:"started_at"`
	TotalDistanceM  *float32      `json:"total_distance_m,omitempty"`
	TotalEnergyKcal *float32      `json:"total_energy_kcal,omitempty"`
}

// WorkoutPage defines model for WorkoutPage.
type WorkoutPage struct {
	Items      *[]Workout `json:"items,omitempty"`
	NextCursor *string    `json:"next_cursor,omitempty"`
}

// WorkoutRoute defines model for WorkoutRoute.
type WorkoutRoute struct {
	Points []RoutePoint `json:"points"`
}

// deviceTokenContextKey is the context key for deviceToken security scheme
type deviceTokenContextKey string

// PostAchievementsJSONBody defines parameters for PostAchievements.
type PostAchievementsJSONBody = []AchievementInput

// GetActivityParams defines parameters for GetActivity.
type GetActivityParams struct {
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To   *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
	Tz   *string             `form:"tz,omitempty" json:"tz,omitempty"`
}

// GetSamplesParams defines parameters for GetSamples.
type GetSamplesParams struct {
	DataType string     `form:"data_type" json:"data_type"`
	From     *time.Time `form:"from,omitempty" json:"from,omitempty"`
	To       *time.Time `form:"to,omitempty" json:"to,omitempty"`
	Cursor   *string    `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit    *int       `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetSleepParams defines parameters for GetSleep.
type GetSleepParams struct {
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To   *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
	Tz   *string             `form:"tz,omitempty" json:"tz,omitempty"`
}

// GetSummaryParams defines parameters for GetSummary.
type GetSummaryParams struct {
	Range GetSummaryParamsRange `form:"range" json:"range"`

	// Metrics a comma-separated list, e.g. stepCount,heartRate,activeEnergy
	Metrics string `form:"metrics" json:"metrics"`

	// Tz IANA tz; if missing, user.time_zone
	Tz   *string             `form:"tz,omitempty" json:"tz,omitempty"`
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To   *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// GetSummaryParamsRange defines parameters for GetSummary.
type GetSummaryParamsRange string

// GetWorkoutsParams defines parameters for GetWorkouts.
type GetWorkoutsParams struct {
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostAchievementsJSONRequestBody defines body for PostAchievements for application/json ContentType.
type PostAchievementsJSONRequestBody = PostAchievementsJSONBody

// PostDevicesJSONRequestBody defines body for PostDevices for application/json ContentType.
type PostDevicesJSONRequestBody = Device

// PostExportJSONRequestBody defines body for PostExport for application/json ContentType.
type PostExportJSONRequestBody = ExportRequest

// PutGoalsJSONRequestBody defines body for PutGoals for application/json ContentType.
type PutGoalsJSONRequestBody = GoalUpdate

// PostIngestJSONRequestBody defines body for PostIngest for application/json ContentType.
type PostIngestJSONRequestBody = IngestBatch

// PutPushPrefsJSONRequestBody defines body for PutPushPrefs for application/json ContentType.
type PutPushPrefsJSONRequestBody = NotifPrefs

// PostPushRegisterJSONRequestBody defines body for PostPushRegister for application/json ContentType.
type PostPushRegisterJSONRequestBody = PushRegister

// PutSettingsJSONRequestBody defines body for PutSettings for application/json ContentType.
type PutSettingsJSONRequestBody = Settings

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Earned badges (monthly, yearly, streak, record, milestone)
	// (GET /achievements)
	GetAchievements(w http.ResponseWriter, r *http.Request)
	// Record badges (idempotent upsert)
	// (POST /achievements)
	PostAchievements(w http.ResponseWriter, r *http.Request)
	// Activity rings (Move/Exercise/Stand), daily value + goal
	// (GET /activity)
	GetActivity(w http.ResponseWriter, r *http.Request, params GetActivityParams)
	// Sign out (revoke the refresh token)
	// (POST /auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request)
	// Refresh the access token with a refresh token
	// (POST /auth/refresh)
	PostAuthRefresh(w http.ResponseWriter, r *http.Request)
	// Connected devices
	// (GET /devices)
	GetDevices(w http.ResponseWriter, r *http.Request)
	// Device registration / heartbeat
	// (POST /devices)
	PostDevices(w http.ResponseWriter, r *http.Request)
	// Export (synchronous download)
	// (POST /export)
	PostExport(w http.ResponseWriter, r *http.Request)
	// Export job status (today always 404 — the export is synchronous)
	// (GET /export/{id})
	GetExportId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Daily goals (steps + rings)
	// (GET /goals)
	GetGoals(w http.ResponseWriter, r *http.Request)
	// Update a goal
	// (PUT /goals)
	PutGoals(w http.ResponseWriter, r *http.Request)
	// Liveness
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// HealthKit chunk upload (samples + workouts + activity summaries + deletions)
	// (POST /ingest)
	PostIngest(w http.ResponseWriter, r *http.Request)
	// Rule-based insights / anomalies
	// (GET /insights)
	GetInsights(w http.ResponseWriter, r *http.Request)
	// Profile
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Notification preferences
	// (PUT /push/prefs)
	PutPushPrefs(w http.ResponseWriter, r *http.Request)
	// APNs push token registration
	// (POST /push/register)
	PostPushRegister(w http.ResponseWriter, r *http.Request)
	// Readiness (DB + Redis + MQ)
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
	// Raw samples (paginated, for debugging/export)
	// (GET /samples)
	GetSamples(w http.ResponseWriter, r *http.Request, params GetSamplesParams)
	// Settings (units, language, time zone, notifications)
	// (GET /settings)
	GetSettings(w http.ResponseWriter, r *http.Request)
	// Change settings
	// (PUT /settings)
	PutSettings(w http.ResponseWriter, r *http.Request)
	// Sleep segments / daily summary
	// (GET /sleep)
	GetSleep(w http.ResponseWriter, r *http.Request, params GetSleepParams)
	// Aggregated dashboard data (timezone-aware)
	// (GET /summary)
	GetSummary(w http.ResponseWriter, r *http.Request, params GetSummaryParams)
	// Workout list (paginated)
	// (GET /workouts)
	GetWorkouts(w http.ResponseWriter, r *http.Request, params GetWorkoutsParams)
	// Workout detail
	// (GET /workouts/{id})
	GetWorkoutsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// A workout's GPS route
	// (GET /workouts/{id}/route)
	GetWorkoutsIdRoute(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Earned badges (monthly, yearly, streak, record, milestone)
// (GET /achievements)
func (_ Unimplemented) GetAchievements(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Record badges (idempotent upsert)
// (POST /achievements)
func (_ Unimplemented) PostAchievements(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Activity rings (Move/Exercise/Stand), daily value + goal
// (GET /activity)
func (_ Unimplemented) GetActivity(w http.ResponseWriter, r *http.Request, params GetActivityParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Sign out (revoke the refresh token)
// (POST /auth/logout)
func (_ Unimplemented) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refresh the access token with a refresh token
// (POST /auth/refresh)
func (_ Unimplemented) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Connected devices
// (GET /devices)
func (_ Unimplemented) GetDevices(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Device registration / heartbeat
// (POST /devices)
func (_ Unimplemented) PostDevices(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Export (synchronous download)
// (POST /export)
func (_ Unimplemented) PostExport(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Export job status (today always 404 — the export is synchronous)
// (GET /export/{id})
func (_ Unimplemented) GetExportId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Daily goals (steps + rings)
// (GET /goals)
func (_ Unimplemented) GetGoals(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a goal
// (PUT /goals)
func (_ Unimplemented) PutGoals(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// HealthKit chunk upload (samples + workouts + activity summaries + deletions)
// (POST /ingest)
func (_ Unimplemented) PostIngest(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rule-based insights / anomalies
// (GET /insights)
func (_ Unimplemented) GetInsights(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Profile
// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Notification preferences
// (PUT /push/prefs)
func (_ Unimplemented) PutPushPrefs(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// APNs push token registration
// (POST /push/register)
func (_ Unimplemented) PostPushRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness (DB + Redis + MQ)
// (GET /readyz)
func (_ Unimplemented) GetReadyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Raw samples (paginated, for debugging/export)
// (GET /samples)
func (_ Unimplemented) GetSamples(w http.ResponseWriter, r *http.Request, params GetSamplesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Settings (units, language, time zone, notifications)
// (GET /settings)
func (_ Unimplemented) GetSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Change settings
// (PUT /settings)
func (_ Unimplemented) PutSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Sleep segments / daily summary
// (GET /sleep)
func (_ Unimplemented) GetSleep(w http.ResponseWriter, r *http.Request, params GetSleepParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Aggregated dashboard data (timezone-aware)
// (GET /summary)
func (_ Unimplemented) GetSummary(w http.ResponseWriter, r *http.Request, params GetSummaryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Workout list (paginated)
// (GET /workouts)
func (_ Unimplemented) GetWorkouts(w http.ResponseWriter, r *http.Request, params GetWorkoutsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Workout detail
// (GET /workouts/{id})
func (_ Unimplemented) GetWorkoutsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// A workout's GPS route
// (GET /workouts/{id}/route)
func (_ Unimplemented) GetWorkoutsIdRoute(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAchievements operation middleware
func (siw *ServerInterfaceWrapper) GetAchievements(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAchievements(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAchievements operation middleware
func (siw *ServerInterfaceWrapper) PostAchievements(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAchievements(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetActivity operation middleware
func (siw *ServerInterfaceWrapper) GetActivity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetActivityParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tz" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tz", r.URL.Query(), &params.Tz, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tz"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tz", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetActivity(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDevices operation middleware
func (siw *ServerInterfaceWrapper) GetDevices(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDevices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDevices operation middleware
func (siw *ServerInterfaceWrapper) PostDevices(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDevices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostExport operation middleware
func (siw *ServerInterfaceWrapper) PostExport(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostExport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExportId operation middleware
func (siw *ServerInterfaceWrapper) GetExportId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExportId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGoals operation middleware
func (siw *ServerInterfaceWrapper) GetGoals(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGoals(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutGoals operation middleware
func (siw *ServerInterfaceWrapper) PutGoals(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutGoals(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostIngest operation middleware
func (siw *ServerInterfaceWrapper) PostIngest(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostIngest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInsights operation middleware
func (siw *ServerInterfaceWrapper) GetInsights(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInsights(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutPushPrefs operation middleware
func (siw *ServerInterfaceWrapper) PutPushPrefs(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutPushPrefs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPushRegister operation middleware
func (siw *ServerInterfaceWrapper) PostPushRegister(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPushRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSamples operation middleware
func (siw *ServerInterfaceWrapper) GetSamples(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSamplesParams

	// ------------- Required query parameter "data_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "data_type", r.URL.Query(), &params.DataType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "data_type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "data_type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSamples(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutSettings operation middleware
func (siw *ServerInterfaceWrapper) PutSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSleep operation middleware
func (siw *ServerInterfaceWrapper) GetSleep(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSleepParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tz" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tz", r.URL.Query(), &params.Tz, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tz"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tz", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSleep(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSummary operation middleware
func (siw *ServerInterfaceWrapper) GetSummary(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSummaryParams

	// ------------- Required query parameter "range" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "range", r.URL.Query(), &params.Range, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "range"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "range", Err: err})
		}
		return
	}

	// ------------- Required query parameter "metrics" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "metrics", r.URL.Query(), &params.Metrics, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "metrics"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "metrics", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tz" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tz", r.URL.Query(), &params.Tz, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tz"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tz", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSummary(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkouts operation middleware
func (siw *ServerInterfaceWrapper) GetWorkouts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkoutsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkouts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkoutsId operation middleware
func (siw *ServerInterfaceWrapper) GetWorkoutsId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkoutsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkoutsIdRoute operation middleware
func (siw *ServerInterfaceWrapper) GetWorkoutsIdRoute(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, DeviceTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkoutsIdRoute(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/achievements", wrapper.GetAchievements)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/achievements", wrapper.PostAchievements)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/activity", wrapper.GetActivity)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.PostAuthRefresh)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/devices", wrapper.GetDevices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/devices", wrapper.PostDevices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/export", wrapper.PostExport)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/export/{id}", wrapper.GetExportId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/goals", wrapper.GetGoals)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/goals", wrapper.PutGoals)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ingest", wrapper.PostIngest)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/insights", wrapper.GetInsights)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/push/prefs", wrapper.PutPushPrefs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/push/register", wrapper.PostPushRegister)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadyz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/samples", wrapper.GetSamples)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/settings", wrapper.GetSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/settings", wrapper.PutSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/sleep", wrapper.GetSleep)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/summary", wrapper.GetSummary)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/workouts", wrapper.GetWorkouts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/workouts/{id}", wrapper.GetWorkoutsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/workouts/{id}/route", wrapper.GetWorkoutsIdRoute)
	})

	return r
}
