// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSamplesByUUID = `-- name: DeleteSamplesByUUID :exec
DELETE FROM samples WHERE user_id = $1 AND source_uuid = ANY($2::text[])
`

type DeleteSamplesByUUIDParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	SourceUuids []string    `json:"source_uuids"`
}

func (q *Queries) DeleteSamplesByUUID(ctx context.Context, arg DeleteSamplesByUUIDParams) error {
	_, err := q.db.Exec(ctx, deleteSamplesByUUID, arg.UserID, arg.SourceUuids)
	return err
}

const deleteSleepByUUID = `-- name: DeleteSleepByUUID :exec
DELETE FROM sleep_segments WHERE user_id = $1 AND source_uuid = ANY($2::text[])
`

type DeleteSleepByUUIDParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	SourceUuids []string    `json:"source_uuids"`
}

func (q *Queries) DeleteSleepByUUID(ctx context.Context, arg DeleteSleepByUUIDParams) error {
	_, err := q.db.Exec(ctx, deleteSleepByUUID, arg.UserID, arg.SourceUuids)
	return err
}

const deleteWorkoutRoute = `-- name: DeleteWorkoutRoute :exec
DELETE FROM workout_route_points WHERE workout_id = $1
`

// Only the first half of a route replacement, ALWAYS inside one transaction with
// an incoming series of points (see internal/ingest/route.go). We never call it
// on its own: a missing route from the client means "I am making no statement",
// not an instruction to delete.
func (q *Queries) DeleteWorkoutRoute(ctx context.Context, workoutID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkoutRoute, workoutID)
	return err
}

const deleteWorkoutsByUUID = `-- name: DeleteWorkoutsByUUID :exec
DELETE FROM workouts WHERE user_id = $1 AND source_uuid = ANY($2::text[])
`

type DeleteWorkoutsByUUIDParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	SourceUuids []string    `json:"source_uuids"`
}

func (q *Queries) DeleteWorkoutsByUUID(ctx context.Context, arg DeleteWorkoutsByUUIDParams) error {
	_, err := q.db.Exec(ctx, deleteWorkoutsByUUID, arg.UserID, arg.SourceUuids)
	return err
}

const getSettings = `-- name: GetSettings :one
SELECT time_zone, locale, unit_system, notif_prefs FROM users WHERE id = $1
`

type GetSettingsRow struct {
	TimeZone   string `json:"time_zone"`
	Locale     string `json:"locale"`
	UnitSystem string `json:"unit_system"`
	NotifPrefs []byte `json:"notif_prefs"`
}

func (q *Queries) GetSettings(ctx context.Context, id pgtype.UUID) (GetSettingsRow, error) {
	row := q.db.QueryRow(ctx, getSettings, id)
	var i GetSettingsRow
	err := row.Scan(
		&i.TimeZone,
		&i.Locale,
		&i.UnitSystem,
		&i.NotifPrefs,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, apple_sub, email, display_name, time_zone, locale, unit_system, notif_prefs, consent_at, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AppleSub,
		&i.Email,
		&i.DisplayName,
		&i.TimeZone,
		&i.Locale,
		&i.UnitSystem,
		&i.NotifPrefs,
		&i.ConsentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkoutIDBySourceUUID = `-- name: GetWorkoutIDBySourceUUID :one
SELECT id FROM workouts WHERE user_id = $1 AND source_uuid = $2
`

type GetWorkoutIDBySourceUUIDParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	SourceUuid string      `json:"source_uuid"`
}

// The client only knows the HealthKit `HKWorkout.uuid`, while the route points
// hang off the server-side `workouts.id` (the same 2A.7 resolution as for
// samples). `user_id` here is also an ownership check: we do not overwrite
// another user's workout route even if the source_uuid matches.
func (q *Queries) GetWorkoutIDBySourceUUID(ctx context.Context, arg GetWorkoutIDBySourceUUIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getWorkoutIDBySourceUUID, arg.UserID, arg.SourceUuid)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSample = `-- name: InsertSample :exec
INSERT INTO samples (
    user_id, ts, data_type, value, unit, workout_source_uuid, workout_id, source_uuid, source_device, source_bundle
) VALUES (
    $1, $2, $3, $4, $5, $6,
    (SELECT w.id FROM workouts w WHERE w.user_id = $1 AND w.source_uuid = $6),
    $7, $8, $9
)
ON CONFLICT (user_id, ts, source_uuid) DO NOTHING
`

type InsertSampleParams struct {
	UserID            pgtype.UUID        `json:"user_id"`
	Ts                pgtype.Timestamptz `json:"ts"`
	DataType          string             `json:"data_type"`
	Value             *float64           `json:"value"`
	Unit              *string            `json:"unit"`
	WorkoutSourceUuid *string            `json:"workout_source_uuid"`
	SourceUuid        string             `json:"source_uuid"`
	SourceDevice      *string            `json:"source_device"`
	SourceBundle      *string            `json:"source_bundle"`
}

// The workout link is resolved from the HealthKit HKWorkout.uuid (2A.7): that is
// all the client knows. We store the raw reference too, so that a workout chunk
// arriving later can supply the missing link (see LinkSamplesToWorkouts).
func (q *Queries) InsertSample(ctx context.Context, arg InsertSampleParams) error {
	_, err := q.db.Exec(ctx, insertSample,
		arg.UserID,
		arg.Ts,
		arg.DataType,
		arg.Value,
		arg.Unit,
		arg.WorkoutSourceUuid,
		arg.SourceUuid,
		arg.SourceDevice,
		arg.SourceBundle,
	)
	return err
}

const linkSamplesToWorkouts = `-- name: LinkSamplesToWorkouts :exec
UPDATE samples s SET workout_id = w.id
FROM workouts w
WHERE s.user_id = $1
  AND s.workout_id IS NULL
  AND s.workout_source_uuid IS NOT NULL
  AND w.user_id = s.user_id
  AND w.source_uuid = s.workout_source_uuid
  AND w.source_uuid = ANY($2::text[])
`

type LinkSamplesToWorkoutsParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	SourceUuids []string    `json:"source_uuids"`
}

// Backfill: wiring up the still-unresolved samples that reference the workouts
// that have just arrived. (Rows already stored are left alone by InsertSample's
// ON CONFLICT DO NOTHING.)
func (q *Queries) LinkSamplesToWorkouts(ctx context.Context, arg LinkSamplesToWorkoutsParams) error {
	_, err := q.db.Exec(ctx, linkSamplesToWorkouts, arg.UserID, arg.SourceUuids)
	return err
}

const listAchievements = `-- name: ListAchievements :many
SELECT user_id, id, kind, code, period, value, unit, thresholds, earned_at, created_at, updated_at FROM achievements
WHERE user_id = $1
ORDER BY earned_at DESC, id
`

// Most recently earned badge first; `id` is only a tie-breaker, so that the order
// of badges earned within the same second does not jump around between pagination
// or reloads.
func (q *Queries) ListAchievements(ctx context.Context, userID pgtype.UUID) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, listAchievements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Achievement
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.UserID,
			&i.ID,
			&i.Kind,
			&i.Code,
			&i.Period,
			&i.Value,
			&i.Unit,
			&i.Thresholds,
			&i.EarnedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitySummary = `-- name: ListActivitySummary :many
SELECT user_id, day, active_energy, active_energy_goal, exercise_minutes, exercise_goal, stand_hours, stand_goal, ingested_at FROM activity_summary
WHERE user_id = $1 AND day >= $2 AND day < $3
ORDER BY day
`

type ListActivitySummaryParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	FromDay pgtype.Date `json:"from_day"`
	ToDay   pgtype.Date `json:"to_day"`
}

// The daily rings (Move/Exercise/Stand), value + goal, over the half-open
// [from_day, to_day) window.
func (q *Queries) ListActivitySummary(ctx context.Context, arg ListActivitySummaryParams) ([]ActivitySummary, error) {
	rows, err := q.db.Query(ctx, listActivitySummary, arg.UserID, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivitySummary
	for rows.Next() {
		var i ActivitySummary
		if err := rows.Scan(
			&i.UserID,
			&i.Day,
			&i.ActiveEnergy,
			&i.ActiveEnergyGoal,
			&i.ExerciseMinutes,
			&i.ExerciseGoal,
			&i.StandHours,
			&i.StandGoal,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevices = `-- name: ListDevices :many
SELECT id, user_id, platform, model, name, time_zone, last_seen_at FROM devices
WHERE user_id = $1
ORDER BY last_seen_at DESC NULLS LAST, platform
`

// The most recently seen device first — the sync-freshness alert looks at this
// first element (docs/16 §2).
func (q *Queries) ListDevices(ctx context.Context, userID pgtype.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Model,
			&i.Name,
			&i.TimeZone,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoals = `-- name: ListGoals :many
SELECT id, user_id, metric, target_value, unit, source, hk_value, updated_at FROM goals WHERE user_id = $1 ORDER BY metric
`

func (q *Queries) ListGoals(ctx context.Context, userID pgtype.UUID) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Metric,
			&i.TargetValue,
			&i.Unit,
			&i.Source,
			&i.HkValue,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSleepSegments = `-- name: ListSleepSegments :many

SELECT started_at, ended_at, stage FROM sleep_segments
WHERE user_id = $1 AND started_at >= $2 AND started_at < $3
ORDER BY started_at
`

type ListSleepSegmentsParams struct {
	UserID pgtype.UUID        `json:"user_id"`
	FromTs pgtype.Timestamptz `json:"from_ts"`
	ToTs   pgtype.Timestamptz `json:"to_ts"`
}

type ListSleepSegmentsRow struct {
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EndedAt   pgtype.Timestamptz `json:"ended_at"`
	Stage     string             `json:"stage"`
}

// (The /v1/workouts + /{id} query is HAND-WRITTEN pgx in internal/workouts: sqlc
//
//	does not correctly type the keyset plus the nullability of the heartRate
//	avg/max LEFT JOIN.)
//
// Sleep segments over the half-open, timezone-aware [from_ts, to_ts) window.
func (q *Queries) ListSleepSegments(ctx context.Context, arg ListSleepSegmentsParams) ([]ListSleepSegmentsRow, error) {
	rows, err := q.db.Query(ctx, listSleepSegments, arg.UserID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSleepSegmentsRow
	for rows.Next() {
		var i ListSleepSegmentsRow
		if err := rows.Scan(&i.StartedAt, &i.EndedAt, &i.Stage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE devices SET
    last_seen_at = now(),
    time_zone    = COALESCE($1, time_zone)
WHERE id = $2 AND user_id = $3
`

type TouchDeviceParams struct {
	TimeZone *string     `json:"time_zone"`
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
}

// The ingest write path's "sign of life": the fresh data IS the heartbeat, no
// separate POST /devices is needed.
func (q *Queries) TouchDevice(ctx context.Context, arg TouchDeviceParams) error {
	_, err := q.db.Exec(ctx, touchDevice, arg.TimeZone, arg.ID, arg.UserID)
	return err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE users SET
    time_zone   = COALESCE($1, time_zone),
    locale      = COALESCE($2, locale),
    unit_system = COALESCE($3, unit_system),
    notif_prefs = COALESCE($4::jsonb, notif_prefs)
WHERE id = $5
RETURNING time_zone, locale, unit_system, notif_prefs
`

type UpdateSettingsParams struct {
	TimeZone   *string     `json:"time_zone"`
	Locale     *string     `json:"locale"`
	UnitSystem *string     `json:"unit_system"`
	NotifPrefs []byte      `json:"notif_prefs"`
	ID         pgtype.UUID `json:"id"`
}

type UpdateSettingsRow struct {
	TimeZone   string `json:"time_zone"`
	Locale     string `json:"locale"`
	UnitSystem string `json:"unit_system"`
	NotifPrefs []byte `json:"notif_prefs"`
}

// A partial update: thanks to the COALESCE, the fields that were not sent stay
// untouched.
func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (UpdateSettingsRow, error) {
	row := q.db.QueryRow(ctx, updateSettings,
		arg.TimeZone,
		arg.Locale,
		arg.UnitSystem,
		arg.NotifPrefs,
		arg.ID,
	)
	var i UpdateSettingsRow
	err := row.Scan(
		&i.TimeZone,
		&i.Locale,
		&i.UnitSystem,
		&i.NotifPrefs,
	)
	return i, err
}

const upsertAchievement = `-- name: UpsertAchievement :exec
INSERT INTO achievements (user_id, id, kind, code, period, value, unit, thresholds, earned_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id, id) DO UPDATE SET
    value      = EXCLUDED.value,
    unit       = EXCLUDED.unit,
    thresholds = EXCLUDED.thresholds,
    updated_at = now()
`

type UpsertAchievementParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	ID         string             `json:"id"`
	Kind       string             `json:"kind"`
	Code       string             `json:"code"`
	Period     *string            `json:"period"`
	Value      *float64           `json:"value"`
	Unit       *string            `json:"unit"`
	Thresholds []int32            `json:"thresholds"`
	EarnedAt   pgtype.Timestamptz `json:"earned_at"`
}

// An upsert, NEVER a delete: the call does not replace the list's contents with
// the submitted set. A reinstalled phone starts with an empty local history — a
// "full replacement" would take that as an instruction, and wipe out badges
// collected over years.
//
// On conflict, `earned_at` STAYS as it was: when it was earned is a fact about
// the past, not about the most recent sync. `value`/`unit`/`thresholds`, on the
// other hand, are updated, because late-arriving HealthKit data can still raise a
// month's step count after the badge was born.
//
// `kind`/`code`/`period` are deliberately left alone: they are encoded by the
// `id` itself (`<kind>:<code>[:<period>]`), so they could not change for the same
// id anyway.
func (q *Queries) UpsertAchievement(ctx context.Context, arg UpsertAchievementParams) error {
	_, err := q.db.Exec(ctx, upsertAchievement,
		arg.UserID,
		arg.ID,
		arg.Kind,
		arg.Code,
		arg.Period,
		arg.Value,
		arg.Unit,
		arg.Thresholds,
		arg.EarnedAt,
	)
	return err
}

const upsertActivitySummary = `-- name: UpsertActivitySummary :exec
INSERT INTO activity_summary (
    user_id, day, active_energy, active_energy_goal, exercise_minutes, exercise_goal, stand_hours, stand_goal
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id, day) DO UPDATE SET
    active_energy = EXCLUDED.active_energy,
    active_energy_goal = EXCLUDED.active_energy_goal,
    exercise_minutes = EXCLUDED.exercise_minutes,
    exercise_goal = EXCLUDED.exercise_goal,
    stand_hours = EXCLUDED.stand_hours,
    stand_goal = EXCLUDED.stand_goal,
    ingested_at = now()
`

type UpsertActivitySummaryParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	Day              pgtype.Date `json:"day"`
	ActiveEnergy     *float64    `json:"active_energy"`
	ActiveEnergyGoal *float64    `json:"active_energy_goal"`
	ExerciseMinutes  *float64    `json:"exercise_minutes"`
	ExerciseGoal     *float64    `json:"exercise_goal"`
	StandHours       *float64    `json:"stand_hours"`
	StandGoal        *float64    `json:"stand_goal"`
}

func (q *Queries) UpsertActivitySummary(ctx context.Context, arg UpsertActivitySummaryParams) error {
	_, err := q.db.Exec(ctx, upsertActivitySummary,
		arg.UserID,
		arg.Day,
		arg.ActiveEnergy,
		arg.ActiveEnergyGoal,
		arg.ExerciseMinutes,
		arg.ExerciseGoal,
		arg.StandHours,
		arg.StandGoal,
	)
	return err
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO devices (user_id, platform, model, name, time_zone, last_seen_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (user_id, platform, (COALESCE(model, ''))) DO UPDATE SET
    name         = COALESCE(EXCLUDED.name, devices.name),
    time_zone    = COALESCE(EXCLUDED.time_zone, devices.time_zone),
    last_seen_at = now()
RETURNING id, user_id, platform, model, name, time_zone, last_seen_at
`

type UpsertDeviceParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Platform string      `json:"platform"`
	Model    *string     `json:"model"`
	Name     *string     `json:"name"`
	TimeZone *string     `json:"time_zone"`
}

// Registration/heartbeat WITHOUT an id: the (platform, model) pair is the key
// (uq_devices_user_platform_model). last_seen_at is always the server's clock —
// this is the alert's source, we do not entrust it to the client.
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, upsertDevice,
		arg.UserID,
		arg.Platform,
		arg.Model,
		arg.Name,
		arg.TimeZone,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Model,
		&i.Name,
		&i.TimeZone,
		&i.LastSeenAt,
	)
	return i, err
}

const upsertDeviceByID = `-- name: UpsertDeviceByID :one
INSERT INTO devices (id, user_id, platform, model, name, time_zone, last_seen_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (id) DO UPDATE SET
    platform     = EXCLUDED.platform,
    model        = COALESCE(EXCLUDED.model, devices.model),
    name         = COALESCE(EXCLUDED.name, devices.name),
    time_zone    = COALESCE(EXCLUDED.time_zone, devices.time_zone),
    last_seen_at = now()
WHERE devices.user_id = EXCLUDED.user_id
RETURNING id, user_id, platform, model, name, time_zone, last_seen_at
`

type UpsertDeviceByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	Platform string      `json:"platform"`
	Model    *string     `json:"model"`
	Name     *string     `json:"name"`
	TimeZone *string     `json:"time_zone"`
}

// Registration/heartbeat with an explicit id. The WHERE on the DO UPDATE is an
// ownership check: we do not write onto another user's device (no returned row →
// the caller answers 409).
func (q *Queries) UpsertDeviceByID(ctx context.Context, arg UpsertDeviceByIDParams) (Device, error) {
	row := q.db.QueryRow(ctx, upsertDeviceByID,
		arg.ID,
		arg.UserID,
		arg.Platform,
		arg.Model,
		arg.Name,
		arg.TimeZone,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Model,
		&i.Name,
		&i.TimeZone,
		&i.LastSeenAt,
	)
	return i, err
}

const upsertGoal = `-- name: UpsertGoal :one
INSERT INTO goals (user_id, metric, target_value, unit, source, hk_value)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, metric) DO UPDATE SET
    target_value = EXCLUDED.target_value,
    unit = EXCLUDED.unit,
    source = EXCLUDED.source,
    hk_value = COALESCE(EXCLUDED.hk_value, goals.hk_value),
    updated_at = now()
RETURNING id, user_id, metric, target_value, unit, source, hk_value, updated_at
`

type UpsertGoalParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Metric      string      `json:"metric"`
	TargetValue float64     `json:"target_value"`
	Unit        string      `json:"unit"`
	Source      string      `json:"source"`
	HkValue     *float64    `json:"hk_value"`
}

func (q *Queries) UpsertGoal(ctx context.Context, arg UpsertGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, upsertGoal,
		arg.UserID,
		arg.Metric,
		arg.TargetValue,
		arg.Unit,
		arg.Source,
		arg.HkValue,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Metric,
		&i.TargetValue,
		&i.Unit,
		&i.Source,
		&i.HkValue,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPushToken = `-- name: UpsertPushToken :one
INSERT INTO push_tokens (user_id, device_id, token, platform, environment)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, token) DO UPDATE SET
    device_id   = COALESCE(EXCLUDED.device_id, push_tokens.device_id),
    platform    = EXCLUDED.platform,
    environment = EXCLUDED.environment,
    updated_at  = now()
RETURNING id, user_id, device_id, token, platform, environment, created_at, updated_at
`

type UpsertPushTokenParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	DeviceID    pgtype.UUID `json:"device_id"`
	Token       string      `json:"token"`
	Platform    string      `json:"platform"`
	Environment string      `json:"environment"`
}

// The key is (user_id, token): the APNs device token IS the identifier, and it
// changes on reinstall. Registering the same token again is an update, not a new
// row — otherwise every app launch would grow the table.
func (q *Queries) UpsertPushToken(ctx context.Context, arg UpsertPushTokenParams) (PushToken, error) {
	row := q.db.QueryRow(ctx, upsertPushToken,
		arg.UserID,
		arg.DeviceID,
		arg.Token,
		arg.Platform,
		arg.Environment,
	)
	var i PushToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.Token,
		&i.Platform,
		&i.Environment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSleepSegment = `-- name: UpsertSleepSegment :exec
INSERT INTO sleep_segments (user_id, source_uuid, started_at, ended_at, stage)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, source_uuid) DO NOTHING
`

type UpsertSleepSegmentParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	SourceUuid string             `json:"source_uuid"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	EndedAt    pgtype.Timestamptz `json:"ended_at"`
	Stage      string             `json:"stage"`
}

func (q *Queries) UpsertSleepSegment(ctx context.Context, arg UpsertSleepSegmentParams) error {
	_, err := q.db.Exec(ctx, upsertSleepSegment,
		arg.UserID,
		arg.SourceUuid,
		arg.StartedAt,
		arg.EndedAt,
		arg.Stage,
	)
	return err
}

const upsertUserByAppleSub = `-- name: UpsertUserByAppleSub :one

INSERT INTO users (apple_sub, email, display_name)
VALUES ($1, $2, $3)
ON CONFLICT (apple_sub) DO UPDATE
    SET email = COALESCE(EXCLUDED.email, users.email)
RETURNING id, apple_sub, email, display_name, time_zone, locale, unit_system, notif_prefs, consent_at, created_at
`

type UpsertUserByAppleSubParams struct {
	AppleSub    string  `json:"apple_sub"`
	Email       *string `json:"email"`
	DisplayName *string `json:"display_name"`
}

// Type-safe queries (sqlc generates Go from these into the internal/db package).
// The timezone-aware summary aggregation is NOT here: sqlc cannot type the
// Timescale time_bucket(.., tz) function → hand-written pgx in internal/summary.
func (q *Queries) UpsertUserByAppleSub(ctx context.Context, arg UpsertUserByAppleSubParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByAppleSub, arg.AppleSub, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AppleSub,
		&i.Email,
		&i.DisplayName,
		&i.TimeZone,
		&i.Locale,
		&i.UnitSystem,
		&i.NotifPrefs,
		&i.ConsentAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertWorkout = `-- name: UpsertWorkout :exec
INSERT INTO workouts (
    user_id, source_uuid, activity_type, started_at, ended_at, total_energy_kcal, total_distance_m, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id, source_uuid) DO NOTHING
`

type UpsertWorkoutParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	SourceUuid      string             `json:"source_uuid"`
	ActivityType    string             `json:"activity_type"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	TotalEnergyKcal *float64           `json:"total_energy_kcal"`
	TotalDistanceM  *float64           `json:"total_distance_m"`
	Metadata        []byte             `json:"metadata"`
}

func (q *Queries) UpsertWorkout(ctx context.Context, arg UpsertWorkoutParams) error {
	_, err := q.db.Exec(ctx, upsertWorkout,
		arg.UserID,
		arg.SourceUuid,
		arg.ActivityType,
		arg.StartedAt,
		arg.EndedAt,
		arg.TotalEnergyKcal,
		arg.TotalDistanceM,
		arg.Metadata,
	)
	return err
}
